version: '3'

services:
  redis:
    image: 'redis:alpine'

  bot:
    build: .
    command: bash -c 'python3 main.py'
    volumes:
      - .:/telebot

    depends_on:
      - redis

  celery:
    build: .
    command: celery worker -A tasks --loglevel=info --beat
    volumes:
      - .:/telebot
    depends_on:
      - bot
      - redis